#%RAML 1.0 Trait

headers:
  client-id:
    type: string
    required: true
    example: "dbfhj-sdbhfbdo8r-yt876t75ty-vbnu76bb"
  client-secret:
    type: string
    required: true
    example: "dbfhj-sdbhfbdo8r-yt876t75ty-vbnu76bb"
        
      