#%RAML 1.0 Trait

queryParameters:
  featureName:
    description: This will show the what type mof feature we are selecting.
    required: true
    type: string
    enum:
      - changecontact
    example: "changecontact"
          